# Generated by Django 4.1.1 on 2022-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_datas_taskdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='task',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
