# Generated by Django 4.1.1 on 2022-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_taskdata_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='task',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
