# Generated by Django 4.1.1 on 2022-09-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_taskdata_task_alter_taskdata_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='time',
        ),
    ]
