# Generated by Django 4.1.1 on 2022-09-27 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_taskdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
