# Generated by Django 4.1.1 on 2023-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_rename_time_taskdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='title',
        ),
        migrations.AddField(
            model_name='taskdata',
            name='desc',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='task',
            field=models.CharField(max_length=30),
        ),
    ]
